version: '3.8'

services:
  loan-risk-app:
    build: .
    container_name: loan-risk-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loan_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  postgres:
    image: postgres:15
    container_name: loan-risk-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    restart: always
